Check if sccache is setup by Prep build

diff --git a/.github/workflows/sanity-checks.yml b/.github/workflows/sanity-checks.yml
--- a/.github/workflows/sanity-checks.yml
+++ b/.github/workflows/sanity-checks.yml
@@ -35,12 +35,15 @@ jobs:
       # Required for integration tests evm interaction
       - name: Install Foundry
         uses: foundry-rs/foundry-toolchain@v1
+      - name: Debug GitHub Environment Variables
+        run: |
+          echo "Printing all variables in GITHUB_ENV:"
+          cat $GITHUB_ENV || echo "GITHUB_ENV file not found or empty"
 
       - name: Runing cargo ${{ matrix.target }}
         run: ./ci/run-check.sh
         env:
           TARGET: ${{ matrix.target }}
-          RUSTC_WRAPPER: "sccache"
 
   benchmark-check:
     if: ${{ !github.event.pull_request.draft }}
@@ -63,10 +66,13 @@ jobs:
           GWIP: ${{ secrets.GWIP_SCCACHE }}
           GSA: ${{ secrets.GSA_SCCACHE }}
 
+      - name: Debug GitHub Environment Variables
+        run: |
+          echo "Printing all variables in GITHUB_ENV:"
+          cat $GITHUB_ENV || echo "GITHUB_ENV file not found or empty"
 
       - name: Runing cargo ${{ matrix.target }}
         run: ./ci/run-check.sh
         env:
           TARGET: benchmark-check
           RUNTIME: ${{ matrix.runtime }}
-          RUSTC_WRAPPER: "sccache"
